// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqmftvdhhnfrgddgsrif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbWZ0dmRoaG5mcmdkZGdzcmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzUzODEsImV4cCI6MjA1OTQ1MTM4MX0.JxbPKAzOBTkokYvFhrOkc-tmk-6U2q0wSeWwKSVeOUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);